version: '3'

services:
  app:
    container_name: dingen-pyramid
    build: ./
    command: pserve development.ini
    volumes:
      - ./:/site:rw
      - ./.local/media:/site/media:rw
    depends_on:
      - postgresql
    ports:
      - "6543:6543"

  postgresql:
    container_name: dingen-postgres
    restart: "no"
    image: postgres:10-alpine
    volumes:
      - ./.local/postgres:/var/lib/postgresql:rw
    environment:
      POSTGRES_USER: dingen
      POSTGRES_PASSWORD: dingen
      POSTGRES_DB: dingen
    ports:
      - "5432:5432"