"""new tags table

Revision ID: 45496b19143e
Revises: 93dbedc78a39
Create Date: 2018-01-21 18:57:05.467836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45496b19143e'
down_revision = '93dbedc78a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_data', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_table('entries__tags',
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name=op.f('fk_entries__tags_entry_id_entries')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_entries__tags_tag_id_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries__tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
