"""blog tables

Revision ID: a99ffbbb7b52
Revises: 
Create Date: 2018-01-22 21:45:39.441100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99ffbbb7b52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entries'))
    )
    op.create_index('entries_index', 'entries', ['title'], unique=False, mysql_length=255)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_data', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index('tag_index', 'tags', ['text_data'], unique=True, mysql_length=64)
    op.create_table('entries__tags',
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name=op.f('fk_entries__tags_entry_id_entries')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_entries__tags_tag_id_tags'))
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], name=op.f('fk_visits_entry_id_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits')),
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('entries__tags')
    op.drop_index('tag_index', table_name='tags')
    op.drop_table('tags')
    op.drop_index('entries_index', table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
